USE inventory_DB;
DROP TABLE IF EXISTS `autoveloce`;
CREATE TABLE `autoveloce` (

  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` text,
  `car_name` text,
  `price` int(11) DEFAULT NULL,
  `miles` int(11) DEFAULT NULL,
  `car_type` text,
  `link` text,
  `exterior_color` text,
  `seller_type` text,
  `ref_price` int(11) DEFAULT NULL,
  `ref_miles` int(11) DEFAULT NULL,
  `dealer_name` text,
  `dealer_street` text,
  `dealer_city` text,
  `dealer_state` text,
  `dealer_country` text,
  `dealer_zip` int(11) DEFAULT NULL,
  `dealer_phone` text,
  `dealer_website` text,
  `year` int(11) DEFAULT NULL,
  `make` text,
  `model` text,
  `trim` text,
  `vehicle_type` text,
  `transmission` text,
  `drivetrain` text,
  `fuel_type` text,
  `engine` text,
  `engine_size` double DEFAULT NULL,
  `engine_block` text,
  `doors` int(11) DEFAULT NULL,
  `cylinders` int(11) DEFAULT NULL,
  `antibrake_sys` text,
  `tank_size` text,
  `seats` int(11) DEFAULT NULL,
  `free_miles` text,
  `city_miles` text,
  `photo_links` text,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
